### ISSUE TITLE
运行docker后，访问ip：端口后报错，解决办法

### ISSUE THREAD

**Issue by wooluo** [wgpsec/DBJ#22]
按照说明，使用docker启动系统后，发现报错：
flask.cli.NoAppException
flask.cli.NoAppException: While importing "flaskr", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/DBJ/flaskr/__init__.py", line 6, in <module>
    from .import admin
  File "/DBJ/flaskr/admin.py", line 20, in <module>
    import dns.resolver #DNS解析
ModuleNotFoundError: No module named 'dns'
发现缺少dns模块……
那么就自己加了一下，在requirements.txt文件中，添加一行
dnspython==2.1.0
重新生成个镜像，然后启动吧，就可以正常使用了，应该是开发者忘记了，添加上吧

**Comment by lapalipi** [comment]
好像是才更新的这个会有。

**Comment by hktalent** [comment]
me too
```
flask.cli.NoAppException
flask.cli.NoAppException: While importing "flaskr", an ImportError was raised:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/DBJ/flaskr/__init__.py", line 6, in <module>
    from .import admin
  File "/DBJ/flaskr/admin.py", line 20, in <module>
    import dns.resolver #DNS解析
ModuleNotFoundError: No module named 'dns'


```
